/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecasimulatorjframe;

import javax.swing.JOptionPane;

/**
 *
 * @author Vanessa
 */
public class TampilanKondisiEksternal extends javax.swing.JFrame {

    /**
     * Creates new form TampilanKondisiEksternal
     */
    double[] bobotPF;
    PublicFactor pf;
    double isiNilaiKK = 0.0;
    double isiNilaiIK = 0.0;
    double isiNilaiKPE = 0.0;
    double isiNilaiKPP = 0.0;
    double isiNilaiKP = 0.0;
    double isiNilaiPSS = 0.0;
    double isiNilaiPS = 0.0;
    double isiNilaiTP = 0.0;
    double isiNilaiDP = 0.0;
    double isiNilaiIFA = 0.0;
    double isiNilaiNSB = 0.0;
    double isiNilaiPP = 0.0;

    public TampilanKondisiEksternal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nilaiPP = new javax.swing.JTextField();
        nilaiDP = new javax.swing.JTextField();
        nilaiNSB = new javax.swing.JTextField();
        nilaiIFA = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        nilaiKeterbukaanPasar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nilaiInfrastrukturKomersial = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nilaiTransferPenelitian = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nilaiPendidikanSMK = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nilaiPendidikanSDSMP = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nilaiKPPajak = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nilaiKPEkonomi = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        nilaiKeuanganKewirausahaan = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SIMULATOR ECA");

        jLabel2.setText("Parameter Setting Kondisi Eksternal :");

        jLabel3.setText("Faktor Publik :");

        jLabel4.setText("Program Pemerintah :");

        jLabel5.setText("Dinamika Pasar :");

        jLabel6.setText("Norma, Sosial dan Budaya :");

        jLabel7.setText("Infrastruktur Fisik dan Akses Layanan :");

        nilaiPP.setText("0");
        nilaiPP.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiPPInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiPPActionPerformed(evt);
            }
        });
        nilaiPP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiPPKeyReleased(evt);
            }
        });

        nilaiDP.setText("0");
        nilaiDP.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiDPInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiDPActionPerformed(evt);
            }
        });
        nilaiDP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiDPKeyReleased(evt);
            }
        });

        nilaiNSB.setText("0");
        nilaiNSB.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiNSBInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiNSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiNSBActionPerformed(evt);
            }
        });
        nilaiNSB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiNSBKeyReleased(evt);
            }
        });

        nilaiIFA.setText("0");
        nilaiIFA.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiIFAInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiIFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiIFAActionPerformed(evt);
            }
        });
        nilaiIFA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiIFAKeyReleased(evt);
            }
        });

        nextButton.setText("NEXT");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("%");

        jLabel9.setText("%");

        jLabel10.setText("%");

        jLabel11.setText("%");

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Keterbukaan Pasar : ");

        nilaiKeterbukaanPasar.setText("0");
        nilaiKeterbukaanPasar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiKeterbukaanPasarInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiKeterbukaanPasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiKeterbukaanPasarActionPerformed(evt);
            }
        });
        nilaiKeterbukaanPasar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiKeterbukaanPasarKeyReleased(evt);
            }
        });

        jLabel13.setText("%");

        jLabel15.setText("Infrastruktur Komersial dan Legal : ");

        nilaiInfrastrukturKomersial.setText("0");
        nilaiInfrastrukturKomersial.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiInfrastrukturKomersialInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiInfrastrukturKomersial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiInfrastrukturKomersialActionPerformed(evt);
            }
        });
        nilaiInfrastrukturKomersial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiInfrastrukturKomersialKeyReleased(evt);
            }
        });

        jLabel16.setText("%");

        jLabel17.setText("Transfer Penelitian dan Pengembangan : ");

        nilaiTransferPenelitian.setText("0");
        nilaiTransferPenelitian.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiTransferPenelitianInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiTransferPenelitian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiTransferPenelitianKeyReleased(evt);
            }
        });

        jLabel18.setText("%");

        jLabel19.setText("Pendidikan Kewirausahaan pada SMK, Profesional dan Universitas : ");

        nilaiPendidikanSMK.setText("0");
        nilaiPendidikanSMK.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiPendidikanSMKInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiPendidikanSMK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiPendidikanSMKKeyReleased(evt);
            }
        });

        jLabel20.setText("%");

        jLabel21.setText("Pendidikan Kewirausahaan pada SD dan SMP :");

        nilaiPendidikanSDSMP.setText("0");
        nilaiPendidikanSDSMP.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiPendidikanSDSMPInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiPendidikanSDSMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiPendidikanSDSMPActionPerformed(evt);
            }
        });
        nilaiPendidikanSDSMP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiPendidikanSDSMPKeyReleased(evt);
            }
        });

        jLabel22.setText("%");

        jLabel23.setText("Kebijakan Pemerintah terkait Pajak :");

        nilaiKPPajak.setText("0");
        nilaiKPPajak.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiKPPajakInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiKPPajak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiKPPajakKeyReleased(evt);
            }
        });

        jLabel24.setText("%");

        jLabel25.setText("Kebijakan Pemerintah terkait Ekonomi :");

        nilaiKPEkonomi.setText("0");
        nilaiKPEkonomi.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiKPEkonomiInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiKPEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiKPEkonomiActionPerformed(evt);
            }
        });
        nilaiKPEkonomi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiKPEkonomiKeyReleased(evt);
            }
        });

        jLabel26.setText("%");

        jLabel27.setText("Keuangan terkait Kewirausahaan :");

        nilaiKeuanganKewirausahaan.setText("0");
        nilaiKeuanganKewirausahaan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiKeuanganKewirausahaanInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nilaiKeuanganKewirausahaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiKeuanganKewirausahaanKeyReleased(evt);
            }
        });

        jLabel28.setText("%");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel29.setText("Total :");

        jLabel30.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(backButton))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel27)
                                                .addComponent(jLabel25)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(nilaiPP)
                                                .addComponent(nilaiKPPajak)
                                                .addComponent(nilaiKPEkonomi)
                                                .addComponent(nilaiKeuanganKewirausahaan, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel21)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nilaiPendidikanSDSMP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(nilaiNSB)
                                                .addComponent(nilaiIFA)
                                                .addComponent(nilaiKeterbukaanPasar)
                                                .addComponent(nilaiDP)
                                                .addComponent(nilaiInfrastrukturKomersial)
                                                .addComponent(nilaiTransferPenelitian)
                                                .addComponent(nilaiPendidikanSMK, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))))
                                    .addComponent(jLabel6))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel28)
                                    .addComponent(nextButton)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel10)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addGap(206, 206, 206))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(nilaiKeuanganKewirausahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(nilaiKPEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(nilaiKPPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nilaiPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nilaiPendidikanSDSMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(nilaiPendidikanSMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(nilaiTransferPenelitian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nilaiInfrastrukturKomersial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nilaiDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nilaiKeterbukaanPasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nilaiIFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel30)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel29)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(backButton)
                                .addComponent(nextButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nilaiNSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(69, 69, 69)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.hide();
        TampilanKondisiKetetanggaan ki = new TampilanKondisiKetetanggaan();
        ki.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_nextButtonActionPerformed

    private void nilaiPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiPPActionPerformed

    }//GEN-LAST:event_nilaiPPActionPerformed

    private void nilaiDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiDPActionPerformed

    }//GEN-LAST:event_nilaiDPActionPerformed

    private void nilaiNSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiNSBActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nilaiNSBActionPerformed

    private void nilaiIFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiIFAActionPerformed

    }//GEN-LAST:event_nilaiIFAActionPerformed
    public void setLabel() {
        double[] arr = new double[12];
        arr[0] = this.nilaiKeuanganKewirausahaan.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiKeuanganKewirausahaan.getText());
        arr[1] = this.nilaiKPEkonomi.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiKPEkonomi.getText());
        arr[2] = this.nilaiKPPajak.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiKPPajak.getText());
        arr[3] = this.nilaiPP.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiPP.getText());
        arr[4] = this.nilaiPendidikanSDSMP.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiPendidikanSDSMP.getText());
        arr[5] = this.nilaiPendidikanSMK.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiPendidikanSMK.getText());
        arr[6] = this.nilaiTransferPenelitian.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiTransferPenelitian.getText());
        arr[7] = this.nilaiInfrastrukturKomersial.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiInfrastrukturKomersial.getText());
        arr[8] = this.nilaiDP.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiDP.getText());
        arr[9] = this.nilaiKeterbukaanPasar.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiKeterbukaanPasar.getText());
        arr[10] = this.nilaiIFA.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiIFA.getText());
        arr[11] = this.nilaiNSB.getText().isEmpty() ? 0: Double.parseDouble(this.nilaiNSB.getText());
        double total = 0;
        for (int i = 0; i < arr.length; i++) {
            total += arr[i];
        }
        this.jTextField1.setText(Double.toString(total));
        
    }
    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        boolean checker = true;
//        String isiNilaiDP;
//        String isiNilaiIFA;
//        String isiNilaiNSB;
//        String isiNilaiPP;

        double[] kumpulanNilaiPF = new double[12];

        if (nilaiDP.getText().equals("")) {
            InputDataHandler.inputDataEksternal("dinamikaPasar", null);
            checker = false;

        } else if (nilaiIFA.getText().equals("")) {
            InputDataHandler.inputDataEksternal("InfrastrukturListrik", null);
            checker = false;
        } else if (nilaiNSB.getText().equals("")) {
            InputDataHandler.inputDataEksternal("NormaSosialBudaya", null);
            checker = false;
        } else if (nilaiPP.getText().equals("")) {
            InputDataHandler.inputDataEksternal("ProgramPemerintah", null);
            checker = false;
        } else if (nilaiInfrastrukturKomersial.getText().equals("")) {
            InputDataHandler.inputDataEksternal("InfrastrukturKomersial", null);
            checker = false;
        } else if (nilaiKPEkonomi.getText().equals("")) {
            InputDataHandler.inputDataEksternal("NilaiKPEkonomi", null);
            checker = false;
        } else if (nilaiKPPajak.getText().equals("")) {
            InputDataHandler.inputDataEksternal("nilaiKPPajak", null);
            checker = false;
        } else if (nilaiKeterbukaanPasar.getText().equals("")) {
            InputDataHandler.inputDataEksternal("nilaiKeterbukaanPasar", null);
            checker = false;
        } else if (nilaiKeuanganKewirausahaan.getText().equals("")) {
            InputDataHandler.inputDataEksternal("nilaiKeuanganKewirausahaan", null);
            checker = false;
        } else if (nilaiPendidikanSDSMP.getText().equals("")) {
            InputDataHandler.inputDataEksternal("nilaiPendidikanSDSMP", null);
            checker = false;
        } else if (nilaiPendidikanSMK.getText().equals("")) {
            InputDataHandler.inputDataEksternal("nilaiPendidikanSMK", null);
            checker = false;
        } else if (nilaiTransferPenelitian.getText().equals("")) {
            InputDataHandler.inputDataEksternal("nilaiTransferPenelitian", null);
            checker = false;
        } else {
            if (!nilaiKeuanganKewirausahaan.equals("")) {
                isiNilaiKK = Double.parseDouble(nilaiKeuanganKewirausahaan.getText()) / 100.0;
                String nilaiKK = Double.toString(isiNilaiKK);
                InputDataHandler.inputDataEksternal("nilaiKeuanganKewirausahaan", nilaiKK);
                kumpulanNilaiPF[0] = Double.parseDouble(InputDataHandler.getValue("nilaiKeuanganKewirausahaan"));
                if (!nilaiKPEkonomi.getText().equals("")) {
                    isiNilaiKPE = Double.parseDouble(nilaiKPEkonomi.getText()) / 100.0;
                    String nilaiKP = Double.toString(isiNilaiKPE);
                    InputDataHandler.inputDataEksternal("nilaiKPEkonomi", nilaiKP);
                    kumpulanNilaiPF[1] = Double.parseDouble(InputDataHandler.getValue("nilaiKPEkonomi"));
                    if (!nilaiKPPajak.getText().equals("")) {
                        isiNilaiKPP = Double.parseDouble(nilaiKPPajak.getText()) / 100.0;
                        String nilaiKPP = Double.toString(isiNilaiKPP);
                        InputDataHandler.inputDataEksternal("nilaiKPPajak", nilaiKPP);
                        kumpulanNilaiPF[2] = Double.parseDouble(InputDataHandler.getValue("nilaiKPPajak"));
                        if (!nilaiPP.getText().equals("")) {
                            isiNilaiPP = Double.parseDouble(nilaiPP.getText()) / 100.0;
                            String nilaiPP = Double.toString(isiNilaiPP);
                            InputDataHandler.inputDataEksternal("ProgramPemerintah", nilaiPP);
                            kumpulanNilaiPF[3] = Double.parseDouble(InputDataHandler.getValue("ProgramPemerintah"));

                            if (!nilaiPendidikanSDSMP.getText().equals("")) {
                                isiNilaiPSS = Double.parseDouble(nilaiPendidikanSDSMP.getText()) / 100.0;
                                String nilaiPSS = Double.toString(isiNilaiPSS);
                                InputDataHandler.inputDataEksternal("nilaiPendidikanSDSMP", nilaiPSS);
                                kumpulanNilaiPF[4] = Double.parseDouble(InputDataHandler.getValue("nilaiPendidikanSDSMP"));
                                if (!nilaiPendidikanSMK.getText().equals("")) {
                                    isiNilaiPS = Double.parseDouble(nilaiPendidikanSMK.getText()) / 100.0;
                                    String nilaiPS = Double.toString(isiNilaiPS);
                                    InputDataHandler.inputDataEksternal("nilaiPendidikanSMK", nilaiPS);
                                    kumpulanNilaiPF[5] = Double.parseDouble(InputDataHandler.getValue("nilaiPendidikanSMK"));
                                    if (!nilaiTransferPenelitian.getText().equals("")) {
                                        isiNilaiTP = Double.parseDouble(nilaiTransferPenelitian.getText()) / 100.0;
                                        String nilaiTP = Double.toString(isiNilaiTP);
                                        InputDataHandler.inputDataEksternal("nilaiTransferPenelitian", nilaiTP);
                                        kumpulanNilaiPF[6] = Double.parseDouble(InputDataHandler.getValue("nilaiTransferPenelitian"));
                                        if (!nilaiInfrastrukturKomersial.getText().equals("")) {
                                            isiNilaiIK = Double.parseDouble(nilaiInfrastrukturKomersial.getText()) / 100.0;
                                            String nilaiIK = Double.toString(isiNilaiIK);
                                            InputDataHandler.inputDataEksternal("nilaiInfrastrukturKomersial", nilaiIK);
                                            kumpulanNilaiPF[7] = Double.parseDouble(InputDataHandler.getValue("nilaiInfrastrukturKomersial"));
                                            if (!nilaiDP.getText().equals("")) {
                                                isiNilaiDP = Double.parseDouble(nilaiDP.getText()) / 100.0;
                                                String nilaiDP = Double.toString(isiNilaiDP);
                                                InputDataHandler.inputDataEksternal("DinamikaPasar", nilaiDP);
                                                kumpulanNilaiPF[8] = Double.parseDouble(InputDataHandler.getValue("DinamikaPasar"));
                                                if (!nilaiKeterbukaanPasar.getText().equals("")) {
                                                    isiNilaiKP = Double.parseDouble(nilaiKeterbukaanPasar.getText()) / 100.0;
                                                    String nilaiKPas = Double.toString(isiNilaiKP);
                                                    InputDataHandler.inputDataEksternal("nilaiKeterbukaanPasar", nilaiKPas);
                                                    kumpulanNilaiPF[9] = Double.parseDouble(InputDataHandler.getValue("nilaiKeterbukaanPasar"));
                                                    if (!nilaiIFA.getText().equals("")) {
                                                        isiNilaiIFA = Double.parseDouble(nilaiIFA.getText()) / 100.0;
                                                        String nilaiIFA = Double.toString(isiNilaiIFA);
                                                        InputDataHandler.inputDataEksternal("InfrastrukturListrik", nilaiIFA);
                                                        kumpulanNilaiPF[10] = Double.parseDouble(InputDataHandler.getValue("InfrastrukturListrik"));
                                                        if (!nilaiNSB.getText().equals("")) {
                                                            isiNilaiNSB = Double.parseDouble(nilaiNSB.getText()) / 100.0;
                                                            String nilaiNSB = Double.toString(isiNilaiNSB);
                                                            InputDataHandler.inputDataEksternal("NormaSosialBudaya", nilaiNSB);
                                                            kumpulanNilaiPF[11] = Double.parseDouble(InputDataHandler.getValue("NormaSosialBudaya"));
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }

                                }
                            }
                        }
                    }
                }
            }
        }
        int totalNilai = 0;
        for (int i = 0; i < kumpulanNilaiPF.length; i++) {
            totalNilai += kumpulanNilaiPF[i] * 100;
        }

        if (totalNilai != 100) {
            JOptionPane.showMessageDialog(null, "The sum of text fields must 100%!");
            checker = false;
        }
        if (checker == true) {
            this.hide();
            TampilanDataWirausaha ks = new TampilanDataWirausaha();
            ks.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "You must fill the text field!");
        }
        InputDataHandler.setDataEksternal(kumpulanNilaiPF);
    }//GEN-LAST:event_nextButtonMouseClicked

    private void nilaiKeterbukaanPasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiKeterbukaanPasarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiKeterbukaanPasarActionPerformed

    private void nilaiInfrastrukturKomersialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiInfrastrukturKomersialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiInfrastrukturKomersialActionPerformed

    private void nilaiPendidikanSDSMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiPendidikanSDSMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiPendidikanSDSMPActionPerformed

    private void nilaiKPEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiKPEkonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiKPEkonomiActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void nilaiKeuanganKewirausahaanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiKeuanganKewirausahaanInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiKeuanganKewirausahaanInputMethodTextChanged

    private void nilaiKPEkonomiInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiKPEkonomiInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiKPEkonomiInputMethodTextChanged

    private void nilaiKPPajakInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiKPPajakInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiKPPajakInputMethodTextChanged

    private void nilaiPPInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiPPInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiPPInputMethodTextChanged

    private void nilaiPendidikanSDSMPInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiPendidikanSDSMPInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiPendidikanSDSMPInputMethodTextChanged

    private void nilaiPendidikanSMKInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiPendidikanSMKInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiPendidikanSMKInputMethodTextChanged

    private void nilaiTransferPenelitianInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiTransferPenelitianInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiTransferPenelitianInputMethodTextChanged

    private void nilaiInfrastrukturKomersialInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiInfrastrukturKomersialInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiInfrastrukturKomersialInputMethodTextChanged

    private void nilaiDPInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiDPInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiDPInputMethodTextChanged

    private void nilaiKeterbukaanPasarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiKeterbukaanPasarInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiKeterbukaanPasarInputMethodTextChanged

    private void nilaiIFAInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiIFAInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiIFAInputMethodTextChanged

    private void nilaiNSBInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiNSBInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiNSBInputMethodTextChanged

    private void nilaiKeuanganKewirausahaanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiKeuanganKewirausahaanKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiKeuanganKewirausahaanKeyReleased

    private void nilaiKPEkonomiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiKPEkonomiKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiKPEkonomiKeyReleased

    private void nilaiKPPajakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiKPPajakKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiKPPajakKeyReleased

    private void nilaiPPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiPPKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiPPKeyReleased

    private void nilaiPendidikanSDSMPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiPendidikanSDSMPKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiPendidikanSDSMPKeyReleased

    private void nilaiPendidikanSMKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiPendidikanSMKKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiPendidikanSMKKeyReleased

    private void nilaiTransferPenelitianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiTransferPenelitianKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiTransferPenelitianKeyReleased

    private void nilaiInfrastrukturKomersialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiInfrastrukturKomersialKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiInfrastrukturKomersialKeyReleased

    private void nilaiDPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiDPKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiDPKeyReleased

    private void nilaiKeterbukaanPasarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiKeterbukaanPasarKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiKeterbukaanPasarKeyReleased

    private void nilaiIFAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiIFAKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiIFAKeyReleased

    private void nilaiNSBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiNSBKeyReleased
        // TODO add your handling code here:
        this.setLabel();
    }//GEN-LAST:event_nilaiNSBKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanKondisiEksternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanKondisiEksternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanKondisiEksternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanKondisiEksternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanKondisiEksternal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JButton nextButton;
    private javax.swing.JTextField nilaiDP;
    private javax.swing.JTextField nilaiIFA;
    private javax.swing.JTextField nilaiInfrastrukturKomersial;
    private javax.swing.JTextField nilaiKPEkonomi;
    private javax.swing.JTextField nilaiKPPajak;
    private javax.swing.JTextField nilaiKeterbukaanPasar;
    private javax.swing.JTextField nilaiKeuanganKewirausahaan;
    private javax.swing.JTextField nilaiNSB;
    private javax.swing.JTextField nilaiPP;
    private javax.swing.JTextField nilaiPendidikanSDSMP;
    private javax.swing.JTextField nilaiPendidikanSMK;
    private javax.swing.JTextField nilaiTransferPenelitian;
    // End of variables declaration//GEN-END:variables
}
