/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecasimulatorjframe;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vanessa
 */
public class TampilanKondisiKetetanggaan extends javax.swing.JFrame {

    /**
     * Creates new form TampilanKondisiKetetanggaan
     */
    JPanel[] kumpulanJPanel;
    int jmlCheckListInternal = 0;
    double[] bobot;
    public TampilanKondisiKetetanggaan() {
        initComponents();

        umurKrgDr.setEnabled(false);
        umurSmDgn.setEnabled(false);
        umurLbhDr.setEnabled(false);
        levelKrgDr.setEnabled(false);
        levelSmDgn.setEnabled(false);
        levelLbhDr.setEnabled(false);
        pendidikanKrgDr.setEnabled(false);
        pendidikanSmDgn.setEnabled(false);
        pendidikanLbhDr.setEnabled(false);
        pendapatanKrgDr.setEnabled(false);
        pendapatanSmDgn.setEnabled(false);
        pendapatanLbhDr.setEnabled(false);

        kumpulanJPanel = new JPanel[]{jUmur, jLevel, jPendidikan, jPendapatan, jJenisKelamin, jLokasi, jbidangUsaha};
        // System.out.println(jUmur.getLocation().getX());
        // System.out.println(jUmur.getLocation().getY());
        for (int i = 0; i < kumpulanJPanel.length; i++) {
            kumpulanJPanel[i].setVisible(false);
            kumpulanJPanel[i].setLocation(29, 103); //ditumpuk di jUmur
        }
        bobot = new double[jmlCheckListInternal];
        int i = 0;
        if (InputDataHandler.checkKey("umurInternal")) {
            kumpulanJPanel[0].setVisible(true);
            jmlCheckListInternal +=1;
            //bobot[i] = Double.parseDouble(InputDataHandler.getValue("umurInternal"));
        }
        if (InputDataHandler.checkKey("levelInternal")) {
            kumpulanJPanel[1].setVisible(true);
            jmlCheckListInternal +=1;
        }
        if (InputDataHandler.checkKey("pendidikanInternal")) {
            kumpulanJPanel[2].setVisible(true);
            jmlCheckListInternal +=1;
        }
        if (InputDataHandler.checkKey("pendapatanInternal")) {
            kumpulanJPanel[3].setVisible(true);
            jmlCheckListInternal +=1;
        }
        if (InputDataHandler.checkKey("jenisKelaminInternal")) {
            kumpulanJPanel[4].setVisible(true);
            jmlCheckListInternal +=1;
        }
        if (InputDataHandler.checkKey("lokasiInternal")) {
            kumpulanJPanel[5].setVisible(true);
            jmlCheckListInternal +=1;
        }
        if (InputDataHandler.checkKey("bidangUsahaInternal")) {
            kumpulanJPanel[6].setVisible(true);
            jmlCheckListInternal +=1;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jUmur = new javax.swing.JPanel();
        umurCBNeg = new javax.swing.JCheckBox();
        umurKrgDr = new javax.swing.JRadioButton();
        umurSmDgn = new javax.swing.JRadioButton();
        umurLbhDr = new javax.swing.JRadioButton();
        jLevel = new javax.swing.JPanel();
        levelCBNeg = new javax.swing.JCheckBox();
        levelKrgDr = new javax.swing.JRadioButton();
        levelSmDgn = new javax.swing.JRadioButton();
        levelLbhDr = new javax.swing.JRadioButton();
        jPendidikan = new javax.swing.JPanel();
        pendidikanCBNeg = new javax.swing.JCheckBox();
        pendidikanKrgDr = new javax.swing.JRadioButton();
        pendidikanSmDgn = new javax.swing.JRadioButton();
        pendidikanLbhDr = new javax.swing.JRadioButton();
        jPendapatan = new javax.swing.JPanel();
        pendapatanCBNeg = new javax.swing.JCheckBox();
        pendapatanKrgDr = new javax.swing.JRadioButton();
        pendapatanSmDgn = new javax.swing.JRadioButton();
        pendapatanLbhDr = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jJenisKelamin = new javax.swing.JPanel();
        jenisKelaminCBNeg = new javax.swing.JCheckBox();
        jbidangUsaha = new javax.swing.JPanel();
        bidangUsahaCBNeg = new javax.swing.JCheckBox();
        jLokasi = new javax.swing.JPanel();
        lokasiCBNeg = new javax.swing.JCheckBox();
        jPendapatan2 = new javax.swing.JPanel();
        pendapatanCBNeg2 = new javax.swing.JCheckBox();
        pendapatanKrgDr2 = new javax.swing.JRadioButton();
        pendapatanSmDgn2 = new javax.swing.JRadioButton();
        pendapatanLbhDr2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SIMULATOR ECA");

        jLabel2.setText("Parameter Setting Kondisi Ketetanggaan :");

        jLabel3.setText("Berdasarkan Relasi :");

        jUmur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        umurCBNeg.setText("UMUR");
        umurCBNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                umurCBNegMouseClicked(evt);
            }
        });
        umurCBNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurCBNegActionPerformed(evt);
            }
        });

        umurKrgDr.setText("<=");

        umurSmDgn.setText("=");

        umurLbhDr.setText(">=");

        javax.swing.GroupLayout jUmurLayout = new javax.swing.GroupLayout(jUmur);
        jUmur.setLayout(jUmurLayout);
        jUmurLayout.setHorizontalGroup(
            jUmurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUmurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(umurCBNeg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(umurKrgDr)
                .addGap(26, 26, 26)
                .addComponent(umurSmDgn)
                .addGap(18, 18, 18)
                .addComponent(umurLbhDr)
                .addContainerGap())
        );
        jUmurLayout.setVerticalGroup(
            jUmurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUmurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jUmurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurCBNeg)
                    .addComponent(umurKrgDr)
                    .addComponent(umurSmDgn)
                    .addComponent(umurLbhDr))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        levelCBNeg.setText("LEVEL");
        levelCBNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levelCBNegMouseClicked(evt);
            }
        });
        levelCBNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelCBNegActionPerformed(evt);
            }
        });

        levelKrgDr.setText("<=");

        levelSmDgn.setText("=");
        levelSmDgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelSmDgnActionPerformed(evt);
            }
        });

        levelLbhDr.setText(">=");
        levelLbhDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelLbhDrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLevelLayout = new javax.swing.GroupLayout(jLevel);
        jLevel.setLayout(jLevelLayout);
        jLevelLayout.setHorizontalGroup(
            jLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(levelCBNeg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(levelKrgDr)
                .addGap(26, 26, 26)
                .addComponent(levelSmDgn)
                .addGap(18, 18, 18)
                .addComponent(levelLbhDr)
                .addContainerGap())
        );
        jLevelLayout.setVerticalGroup(
            jLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLevelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelCBNeg)
                    .addComponent(levelKrgDr)
                    .addComponent(levelSmDgn)
                    .addComponent(levelLbhDr))
                .addContainerGap())
        );

        jPendidikan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pendidikanCBNeg.setText("PENDIDIKAN");
        pendidikanCBNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendidikanCBNegMouseClicked(evt);
            }
        });
        pendidikanCBNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendidikanCBNegActionPerformed(evt);
            }
        });

        pendidikanKrgDr.setText("<=");

        pendidikanSmDgn.setText("=");

        pendidikanLbhDr.setText(">=");

        javax.swing.GroupLayout jPendidikanLayout = new javax.swing.GroupLayout(jPendidikan);
        jPendidikan.setLayout(jPendidikanLayout);
        jPendidikanLayout.setHorizontalGroup(
            jPendidikanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPendidikanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendidikanCBNeg)
                .addGap(95, 95, 95)
                .addComponent(pendidikanKrgDr)
                .addGap(27, 27, 27)
                .addComponent(pendidikanSmDgn)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(pendidikanLbhDr)
                .addContainerGap())
        );
        jPendidikanLayout.setVerticalGroup(
            jPendidikanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPendidikanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPendidikanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendidikanCBNeg)
                    .addComponent(pendidikanKrgDr)
                    .addComponent(pendidikanSmDgn)
                    .addComponent(pendidikanLbhDr))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPendapatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pendapatanCBNeg.setText("PENDAPATAN");
        pendapatanCBNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendapatanCBNegMouseClicked(evt);
            }
        });
        pendapatanCBNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendapatanCBNegActionPerformed(evt);
            }
        });

        pendapatanKrgDr.setText("<=");

        pendapatanSmDgn.setText("=");

        pendapatanLbhDr.setText(">=");

        javax.swing.GroupLayout jPendapatanLayout = new javax.swing.GroupLayout(jPendapatan);
        jPendapatan.setLayout(jPendapatanLayout);
        jPendapatanLayout.setHorizontalGroup(
            jPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPendapatanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendapatanCBNeg)
                .addGap(92, 92, 92)
                .addComponent(pendapatanKrgDr)
                .addGap(27, 27, 27)
                .addComponent(pendapatanSmDgn)
                .addGap(18, 18, 18)
                .addComponent(pendapatanLbhDr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPendapatanLayout.setVerticalGroup(
            jPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPendapatanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendapatanCBNeg)
                    .addComponent(pendapatanKrgDr)
                    .addComponent(pendapatanSmDgn)
                    .addComponent(pendapatanLbhDr))
                .addContainerGap())
        );

        jenisKelaminCBNeg.setText("JENIS KELAMIN");
        jenisKelaminCBNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKelaminCBNegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jJenisKelaminLayout = new javax.swing.GroupLayout(jJenisKelamin);
        jJenisKelamin.setLayout(jJenisKelaminLayout);
        jJenisKelaminLayout.setHorizontalGroup(
            jJenisKelaminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jJenisKelaminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisKelaminCBNeg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jJenisKelaminLayout.setVerticalGroup(
            jJenisKelaminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jJenisKelaminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jenisKelaminCBNeg)
                .addContainerGap())
        );

        bidangUsahaCBNeg.setText("BIDANG USAHA");
        bidangUsahaCBNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidangUsahaCBNegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jbidangUsahaLayout = new javax.swing.GroupLayout(jbidangUsaha);
        jbidangUsaha.setLayout(jbidangUsahaLayout);
        jbidangUsahaLayout.setHorizontalGroup(
            jbidangUsahaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbidangUsahaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bidangUsahaCBNeg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jbidangUsahaLayout.setVerticalGroup(
            jbidangUsahaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbidangUsahaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bidangUsahaCBNeg)
                .addContainerGap())
        );

        lokasiCBNeg.setText("LOKASI");
        lokasiCBNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasiCBNegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLokasiLayout = new javax.swing.GroupLayout(jLokasi);
        jLokasi.setLayout(jLokasiLayout);
        jLokasiLayout.setHorizontalGroup(
            jLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLokasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lokasiCBNeg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLokasiLayout.setVerticalGroup(
            jLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLokasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lokasiCBNeg)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbidangUsaha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLokasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jJenisKelamin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbidangUsaha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPendapatan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pendapatanCBNeg2.setText("PENDAPATAN");
        pendapatanCBNeg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendapatanCBNeg2ActionPerformed(evt);
            }
        });

        pendapatanKrgDr2.setText("<=");

        pendapatanSmDgn2.setText("=");

        pendapatanLbhDr2.setText(">=");

        javax.swing.GroupLayout jPendapatan2Layout = new javax.swing.GroupLayout(jPendapatan2);
        jPendapatan2.setLayout(jPendapatan2Layout);
        jPendapatan2Layout.setHorizontalGroup(
            jPendapatan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPendapatan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendapatanCBNeg2)
                .addGap(92, 92, 92)
                .addComponent(pendapatanKrgDr2)
                .addGap(27, 27, 27)
                .addComponent(pendapatanSmDgn2)
                .addGap(18, 18, 18)
                .addComponent(pendapatanLbhDr2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPendapatan2Layout.setVerticalGroup(
            jPendapatan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPendapatan2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPendapatan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendapatanCBNeg2)
                    .addComponent(pendapatanKrgDr2)
                    .addComponent(pendapatanSmDgn2)
                    .addComponent(pendapatanLbhDr2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jUmur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLevel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPendidikan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(jPendapatan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3821, 3821, 3821))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(2122, 2122, 2122)
                    .addComponent(jPendapatan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(2122, Short.MAX_VALUE)))
        );

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setText("NEXT");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(nextButton))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(nextButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void levelCBNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelCBNegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelCBNegActionPerformed

    private void levelLbhDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelLbhDrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelLbhDrActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.hide();
        TampilanKondisiInternal ki = new TampilanKondisiInternal();
        ki.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nextButtonActionPerformed

    private void umurCBNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurCBNegActionPerformed
        // TODO add your handling code here:
        ButtonGroup group = new ButtonGroup();
        group.add(umurKrgDr);
        group.add(umurSmDgn);
        group.add(umurLbhDr);
    }//GEN-LAST:event_umurCBNegActionPerformed

    private void pendidikanCBNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendidikanCBNegActionPerformed
        // TODO add your handling code here:
        ButtonGroup group = new ButtonGroup();
        group.add(pendidikanKrgDr);
        group.add(pendidikanSmDgn);
        group.add(pendidikanLbhDr);
    }//GEN-LAST:event_pendidikanCBNegActionPerformed

    private void pendapatanCBNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendapatanCBNegActionPerformed
        // TODO add your handling code here:
        ButtonGroup group = new ButtonGroup();
        group.add(pendapatanKrgDr);
        group.add(pendapatanSmDgn);
        group.add(pendapatanLbhDr);
    }//GEN-LAST:event_pendapatanCBNegActionPerformed

    private void levelSmDgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelSmDgnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelSmDgnActionPerformed

    private void jenisKelaminCBNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKelaminCBNegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisKelaminCBNegActionPerformed

    private void pendapatanCBNeg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendapatanCBNeg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendapatanCBNeg2ActionPerformed

    private void bidangUsahaCBNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidangUsahaCBNegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidangUsahaCBNegActionPerformed

    private void lokasiCBNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasiCBNegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lokasiCBNegActionPerformed

    private void umurCBNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_umurCBNegMouseClicked
        if (umurCBNeg.isSelected()) {
            umurKrgDr.setEnabled(true);
            umurSmDgn.setEnabled(true);
            umurLbhDr.setEnabled(true);
        } else {
            umurKrgDr.setEnabled(false);
            umurSmDgn.setEnabled(false);
            umurLbhDr.setEnabled(false);
        }
    }//GEN-LAST:event_umurCBNegMouseClicked

    private void levelCBNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelCBNegMouseClicked
        if (levelCBNeg.isSelected()) {
            levelKrgDr.setEnabled(true);
            levelSmDgn.setEnabled(true);
            levelLbhDr.setEnabled(true);
        } else {
            levelKrgDr.setEnabled(false);
            levelSmDgn.setEnabled(false);
            levelLbhDr.setEnabled(false);
        }
    }//GEN-LAST:event_levelCBNegMouseClicked

    private void pendidikanCBNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendidikanCBNegMouseClicked
        if (pendidikanCBNeg.isSelected()) {
            pendidikanKrgDr.setEnabled(true);
            pendidikanSmDgn.setEnabled(true);
            pendidikanLbhDr.setEnabled(true);
        } else {
            pendidikanKrgDr.setEnabled(false);
            pendidikanSmDgn.setEnabled(false);
            pendidikanLbhDr.setEnabled(false);
        }
    }//GEN-LAST:event_pendidikanCBNegMouseClicked

    private void pendapatanCBNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendapatanCBNegMouseClicked
        if (pendapatanCBNeg.isSelected()) {
            pendapatanKrgDr.setEnabled(true);
            pendapatanSmDgn.setEnabled(true);
            pendapatanLbhDr.setEnabled(true);
        } else {
            pendapatanKrgDr.setEnabled(false);
            pendapatanSmDgn.setEnabled(false);
            pendapatanLbhDr.setEnabled(false);
        }
    }//GEN-LAST:event_pendapatanCBNegMouseClicked

    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        boolean checker = true;
        String nilaiRB = "";
        
        double[] bobot = new double[InputDataHandler.getKetetanggaan()];
        
        // set relasi 0 kalau ga checkboxnya gadipilih
        // set relasi 1 kalau kurang dari sama dengan
        // set relasi 2 kalau sama dengan
        // set relasi 3 kalau lebih dari sama dengan
        
        int n = 0;
        int[] kumpulanNilaiRelasi = new int[4];
        //umur
        if (umurCBNeg.isSelected()) {
            InputDataHandler.jmlChecklist();
            //System.out.println(jmlCheckList);
            // kalo radio button umurKrgDr ga diisi, check umurSmDgn
            if (!umurKrgDr.isSelected()) {
                checker = false;
                // kalo radio button umurSmDgn ga diisi, check umurLbhDr
                if (!umurSmDgn.isSelected()) {
                    checker = false;
                    // kalo radio button umurLbhDr ga diisi, checker = false
                    if (!umurLbhDr.isSelected()) {
                        checker = false;
                    } // kalo radio button umurLbhDr diisi lsg dimasukin datanya ke data handler
                    else {
                        InputDataHandler.inputDataKetetanggaan("umurLbhDr", umurLbhDr.getText());
                        nilaiRB = InputDataHandler.getValue("umurLbhDr");
                        if (nilaiRB.equals(">=")) {
                            nilaiRB = "3";
                        }
                        kumpulanNilaiRelasi[n] = Integer.parseInt(nilaiRB);
                        n++;
                        // System.out.println(kumpulanNilaiRelasi[0]);
                        checker = true;
                    }
                } // kalo radio button umurSmDgn diisi, lsg masukin datanya ke data handler
                else {
                    InputDataHandler.inputDataKetetanggaan("umurSmDgn", umurSmDgn.getText());
                    nilaiRB = InputDataHandler.getValue("umurSmDgn");
                    if (nilaiRB.equals("=")) {
                        nilaiRB = "2";
                    }
                    kumpulanNilaiRelasi[n] = Integer.parseInt(nilaiRB);
                    n++;
                    // System.out.println(kumpulanNilaiRelasi[0]);
                    checker = true;
                }
            } // kalo radio button umurKrgDr diisi lsg true n nilainya dimasukin ke data handler
            else {
                InputDataHandler.inputDataKetetanggaan("umurKurangDari", umurKrgDr.getText());
                nilaiRB = InputDataHandler.getValue("umurKurangDari");
                if (nilaiRB.equals("<=")) {
                    nilaiRB = "1";
                }
                kumpulanNilaiRelasi[n] = Integer.parseInt(nilaiRB);
                n++;
                //  System.out.println(kumpulanNilaiRelasi[0]);
                checker = true;
            }

        } else {
            nilaiRB = "0";
            kumpulanNilaiRelasi[n] = Integer.parseInt(nilaiRB);
            n++;
        }

        // level
        if (levelCBNeg.isSelected()) {
            InputDataHandler.jmlChecklist();
            // kalo radio button levelKrgDr ga diisi, check levelSmDgn
            if (!levelKrgDr.isSelected()) {
                // kalo radio button levelSmDgn ga diisi, check levelLbhDr
                if (!levelSmDgn.isSelected()) {
                    // kalo radio button levelLbhDr ga diisi, checker = false
                    if (!levelLbhDr.isSelected()) {
                        checker = false;
                    } // kalo radio button levelLbhDr diisi lsg dimasukin datanya ke data handler
                    else {
                        InputDataHandler.inputDataKetetanggaan("levelLbhDr", levelLbhDr.getText());
                        nilaiRB = InputDataHandler.getValue("levelLbhDr");
                        if (nilaiRB.equals(">=")) {
                            nilaiRB = "3";
                        }
                        kumpulanNilaiRelasi[1] = Integer.parseInt(nilaiRB);
                        checker = true;
                    }
                } // kalo radio button levelSmDgn diisi, lsg masukin datanya ke data handler
                else {
                    InputDataHandler.inputDataKetetanggaan("levelSmDgn", levelSmDgn.getText());
                    nilaiRB = InputDataHandler.getValue("levelSmDgn");
                    if (nilaiRB.equals("=")) {
                        nilaiRB = "2";
                    }
                    kumpulanNilaiRelasi[1] = Integer.parseInt(nilaiRB);
                    checker = true;
                }
            } // kalo radio button levelKrgDr diisi lsg true n nilainya dimasukin ke data handler
            else {
                InputDataHandler.inputDataKetetanggaan("levelKurangDari", levelKrgDr.getText());
                nilaiRB = InputDataHandler.getValue("levelKurangDari");
                if (nilaiRB.equals("<=")) {
                    nilaiRB = "1";
                }
                kumpulanNilaiRelasi[1] = Integer.parseInt(nilaiRB);
                checker = true;
            }
        } else {
            nilaiRB = "0";
            kumpulanNilaiRelasi[1] = Integer.parseInt(nilaiRB);
        }

        //pendidikan
        if (pendidikanCBNeg.isSelected()) {
            InputDataHandler.jmlChecklist();
            // kalo radio button pendidikanKrgDr ga diisi, check pendidikanSmDgn
            if (!pendidikanKrgDr.isSelected()) {
                // kalo radio button pendidikanSmDgn ga diisi, check pendidikanLbhDr
                if (!pendidikanSmDgn.isSelected()) {
                    // kalo radio button pendidikanLbhDr ga diisi, checker = false
                    if (!pendidikanLbhDr.isSelected()) {
                        checker = false;
                    } // kalo radio button pendidikanLbhDr diisi lsg dimasukin datanya ke data handler
                    else {
                        InputDataHandler.inputDataKetetanggaan("pendidikanLbhDr", pendidikanLbhDr.getText());
                        nilaiRB = InputDataHandler.getValue("pendidikanLbhDr");
                        if (nilaiRB.equals(">=")) {
                            nilaiRB = "3";
                        }
                        kumpulanNilaiRelasi[2] = Integer.parseInt(nilaiRB);
                        checker = true;
                    }
                } // kalo radio button pendidikanSmDgn diisi, lsg masukin datanya ke data handler
                else {
                    InputDataHandler.inputDataKetetanggaan("pendidikanSmDgn", pendidikanSmDgn.getText());
                    nilaiRB = InputDataHandler.getValue("pendidikanSmDgn");
                    if (nilaiRB.equals("=")) {
                        nilaiRB = "2";
                    }
                    kumpulanNilaiRelasi[2] = Integer.parseInt(nilaiRB);
                    checker = true;
                }
            } // kalo radio button pendidikanKrgDr diisi lsg true n nilainya dimasukin ke data handler
            else {
                InputDataHandler.inputDataKetetanggaan("pendidikanKurangDari", pendidikanKrgDr.getText());
                nilaiRB = InputDataHandler.getValue("pendidikanKurangDari");
                if (nilaiRB.equals("<=")) {
                    nilaiRB = "1";
                }
                kumpulanNilaiRelasi[2] = Integer.parseInt(nilaiRB);
                checker = true;
            }
        } else {
            nilaiRB = "0";
            kumpulanNilaiRelasi[2] = Integer.parseInt(nilaiRB);
        }

        //pendapatan
        if (pendapatanCBNeg.isSelected()) {
            InputDataHandler.jmlChecklist();
            // kalo radio button pendapatanKrgDr ga diisi, check pendapatanSmDgn
            if (!pendapatanKrgDr.isSelected()) {
                // kalo radio button pendapatanSmDgn ga diisi, check pendapatanLbhDr
                if (!pendapatanSmDgn.isSelected()) {
                    // kalo radio button pendapatanLbhDr ga diisi, checker = false
                    if (!pendapatanLbhDr.isSelected()) {
                        checker = false;
                    } // kalo radio button pendapatanLbhDr diisi lsg dimasukin datanya ke data handler
                    else {
                        InputDataHandler.inputDataKetetanggaan("pendapatanLbhDr", pendapatanLbhDr.getText());
                        nilaiRB = InputDataHandler.getValue("pendapatanLbhDr");
                        if (nilaiRB.equals(">=")) {
                            nilaiRB = "3";
                        }
                        kumpulanNilaiRelasi[3] = Integer.parseInt(nilaiRB);
                        checker = true;
                    }
                } // kalo radio button pendapatanSmDgn diisi, lsg masukin datanya ke data handler
                else {
                    InputDataHandler.inputDataKetetanggaan("pendapatanSmDgn", pendapatanSmDgn.getText());
                    nilaiRB = InputDataHandler.getValue("pendapatanSmDgn");
                    if (nilaiRB.equals("=")) {
                        nilaiRB = "2";
                    }
                    kumpulanNilaiRelasi[3] = Integer.parseInt(nilaiRB);
                    checker = true;
                }
            } // kalo radio button pendapatanKrgDr diisi lsg true n nilainya dimasukin ke data handler
            else {
                InputDataHandler.inputDataKetetanggaan("pendapatanKurangDari", pendapatanKrgDr.getText());
                nilaiRB = InputDataHandler.getValue("pendapatanKurangDari");
                if (nilaiRB.equals("<=")) {
                    nilaiRB = "1";
                }
                kumpulanNilaiRelasi[3] = Integer.parseInt(nilaiRB);
                checker = true;
            }
        } else {
            nilaiRB = "0";
            kumpulanNilaiRelasi[3] = Integer.parseInt(nilaiRB);
        }
        
        InputDataHandler.setRelation(kumpulanNilaiRelasi);
//        System.out.println(InputDataHandler.getRelation());

        if (jenisKelaminCBNeg.isSelected()) {
            InputDataHandler.jmlChecklist += 1;
        }
        if (lokasiCBNeg.isSelected()) {
            InputDataHandler.jmlChecklist += 1;
        }
        if (bidangUsahaCBNeg.isSelected()) {
            InputDataHandler.jmlChecklist += 1;
        }

        if (InputDataHandler.jmlChecklist == 0) {
            checker = false;
            //JOptionPane.showMessageDialog(null, "Check box is empty, you must fill it first!");
        }
        if (checker == true) {
            this.hide();
            TampilanKondisiEksternal ke = new TampilanKondisiEksternal();
            ke.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "You cannot move to the other page because you must fill checkbox or radio button first!");
        }
    }//GEN-LAST:event_nextButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanKondisiKetetanggaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanKondisiKetetanggaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanKondisiKetetanggaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanKondisiKetetanggaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanKondisiKetetanggaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JCheckBox bidangUsahaCBNeg;
    private javax.swing.JPanel jJenisKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jLevel;
    private javax.swing.JPanel jLokasi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPendapatan;
    private javax.swing.JPanel jPendapatan2;
    private javax.swing.JPanel jPendidikan;
    private javax.swing.JPanel jUmur;
    private javax.swing.JPanel jbidangUsaha;
    private javax.swing.JCheckBox jenisKelaminCBNeg;
    private javax.swing.JCheckBox levelCBNeg;
    private javax.swing.JRadioButton levelKrgDr;
    private javax.swing.JRadioButton levelLbhDr;
    private javax.swing.JRadioButton levelSmDgn;
    private javax.swing.JCheckBox lokasiCBNeg;
    public javax.swing.JButton nextButton;
    private javax.swing.JCheckBox pendapatanCBNeg;
    private javax.swing.JCheckBox pendapatanCBNeg2;
    private javax.swing.JRadioButton pendapatanKrgDr;
    private javax.swing.JRadioButton pendapatanKrgDr2;
    private javax.swing.JRadioButton pendapatanLbhDr;
    private javax.swing.JRadioButton pendapatanLbhDr2;
    private javax.swing.JRadioButton pendapatanSmDgn;
    private javax.swing.JRadioButton pendapatanSmDgn2;
    private javax.swing.JCheckBox pendidikanCBNeg;
    private javax.swing.JRadioButton pendidikanKrgDr;
    private javax.swing.JRadioButton pendidikanLbhDr;
    private javax.swing.JRadioButton pendidikanSmDgn;
    private javax.swing.JCheckBox umurCBNeg;
    private javax.swing.JRadioButton umurKrgDr;
    private javax.swing.JRadioButton umurLbhDr;
    private javax.swing.JRadioButton umurSmDgn;
    // End of variables declaration//GEN-END:variables
}
